apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: clixx-prod

resources:
  - namespace-clixx.yaml
  - storage-class.yaml
  - pvc.yaml
  - clixx-deployment.yaml
  - clixx-lb-np.yaml

configMapGenerator:
  - name: wp-config-template
    files:
      - wp-config.php